name: barber_shop
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  random_string: ^2.1.0
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^2.5.4
  flutter_signin_button: ^1.1.0
  google_fonts: ^1.1.1
  intl: ^0.16.1
  provider: ^4.3.2+4
  image_picker: ^0.6.7+21
  stripe_payment: ^1.0.9
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.5.0
  flushbar: ^1.10.4
  firebase_messaging: ^7.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

